In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("data_cleaning_practice_dataset.csv")

In [6]:
df

       Name  Gender   Age       City Department     Salary               Email
0     Tariq    Male  47.0    Karachi     Sales   123609.72   tariq76@gmail.com
1      Hina  Female  26.0     Quetta         HR  125683.94    hina90@gmail.com
2     Usman    Male  36.0     lahore     Sales         NaN   usman71@gmail.com
3      Sana  Female  21.0     Quetta    Finance  147901.41    sana72@gmail.com
4    Ayesha    Male  40.0     lahore         HR  123880.80  ayesha25@gmail.com
..      ...     ...   ...        ...        ...        ...                 ...
495    Zara  Female  56.0     quetta         IT        NaN    zara35@gmail.com
496   Usman    Male   NaN     Lahore      Sales  107909.74   usman20@gmail.com
497   Ahmed    Male  20.0  Islamabad      Sales        NaN   ahmed99@gmail.com
498   Ahmed  Female   NaN     Lahore         IT   82915.36   ahmed80@gmail.com
499   Tariq    Male   NaN  Islamabad    Finance  122337.81   tariq64@gmail.com

[500 rows x 7 columns]

In [7]:
df.dtypes

Name           object
Gender         object
Age           float64
City           object
Department     object
Salary        float64
Email          object
dtype: object

In [10]:
df.isnull().sum()

Name            0
Gender          0
Age           248
City            0
Department      0
Salary        252
Email           0
dtype: int64

In [12]:
df["Age"].fillna(df["Age"].median(), inplace = True)

In [13]:
df

       Name  Gender   Age       City Department     Salary               Email
0     Tariq    Male  47.0    Karachi     Sales   123609.72   tariq76@gmail.com
1      Hina  Female  26.0     Quetta         HR  125683.94    hina90@gmail.com
2     Usman    Male  36.0     lahore     Sales         NaN   usman71@gmail.com
3      Sana  Female  21.0     Quetta    Finance  147901.41    sana72@gmail.com
4    Ayesha    Male  40.0     lahore         HR  123880.80  ayesha25@gmail.com
..      ...     ...   ...        ...        ...        ...                 ...
495    Zara  Female  56.0     quetta         IT        NaN    zara35@gmail.com
496   Usman    Male  41.0     Lahore      Sales  107909.74   usman20@gmail.com
497   Ahmed    Male  20.0  Islamabad      Sales        NaN   ahmed99@gmail.com
498   Ahmed  Female  41.0     Lahore         IT   82915.36   ahmed80@gmail.com
499   Tariq    Male  41.0  Islamabad    Finance  122337.81   tariq64@gmail.com

[500 rows x 7 columns]

In [14]:
df["Age"] = df["Age"].astype(int)

In [15]:
df

       Name  Gender  Age       City Department     Salary               Email
0     Tariq    Male   47    Karachi     Sales   123609.72   tariq76@gmail.com
1      Hina  Female   26     Quetta         HR  125683.94    hina90@gmail.com
2     Usman    Male   36     lahore     Sales         NaN   usman71@gmail.com
3      Sana  Female   21     Quetta    Finance  147901.41    sana72@gmail.com
4    Ayesha    Male   40     lahore         HR  123880.80  ayesha25@gmail.com
..      ...     ...  ...        ...        ...        ...                 ...
495    Zara  Female   56     quetta         IT        NaN    zara35@gmail.com
496   Usman    Male   41     Lahore      Sales  107909.74   usman20@gmail.com
497   Ahmed    Male   20  Islamabad      Sales        NaN   ahmed99@gmail.com
498   Ahmed  Female   41     Lahore         IT   82915.36   ahmed80@gmail.com
499   Tariq    Male   41  Islamabad    Finance  122337.81   tariq64@gmail.com

[500 rows x 7 columns]

In [16]:
df["Salary"].fillna(df["Salary"].median(), inplace = True)

C:\Users\Eniholla\AppData\Local\Temp\ipykernel_19572\1121388271.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Salary"].fillna(df["Salary"].median(), inplace = True)

In [17]:
df

       Name  Gender  Age       City Department      Salary               Email
0     Tariq    Male   47    Karachi     Sales   123609.720   tariq76@gmail.com
1      Hina  Female   26     Quetta         HR  125683.940    hina90@gmail.com
2     Usman    Male   36     lahore     Sales    94056.675   usman71@gmail.com
3      Sana  Female   21     Quetta    Finance  147901.410    sana72@gmail.com
4    Ayesha    Male   40     lahore         HR  123880.800  ayesha25@gmail.com
..      ...     ...  ...        ...        ...         ...                 ...
495    Zara  Female   56     quetta         IT   94056.675    zara35@gmail.com
496   Usman    Male   41     Lahore      Sales  107909.740   usman20@gmail.com
497   Ahmed    Male   20  Islamabad      Sales   94056.675   ahmed99@gmail.com
498   Ahmed  Female   41     Lahore         IT   82915.360   ahmed80@gmail.com
499   Tariq    Male   41  Islamabad    Finance  122337.810   tariq64@gmail.com

[500 rows x 7 columns]

In [19]:
df["Salary"] = df["Salary"].astype(int).apply(lambda x: f"${x:,}")

In [20]:
df

       Name  Gender  Age       City Department    Salary               Email
0     Tariq    Male   47    Karachi     Sales   $123,609   tariq76@gmail.com
1      Hina  Female   26     Quetta         HR  $125,683    hina90@gmail.com
2     Usman    Male   36     lahore     Sales    $94,056   usman71@gmail.com
3      Sana  Female   21     Quetta    Finance  $147,901    sana72@gmail.com
4    Ayesha    Male   40     lahore         HR  $123,880  ayesha25@gmail.com
..      ...     ...  ...        ...        ...       ...                 ...
495    Zara  Female   56     quetta         IT   $94,056    zara35@gmail.com
496   Usman    Male   41     Lahore      Sales  $107,909   usman20@gmail.com
497   Ahmed    Male   20  Islamabad      Sales   $94,056   ahmed99@gmail.com
498   Ahmed  Female   41     Lahore         IT   $82,915   ahmed80@gmail.com
499   Tariq    Male   41  Islamabad    Finance  $122,337   tariq64@gmail.com

[500 rows x 7 columns]

In [21]:
df["Email"] = df["Email"].str.strip()

In [22]:
df

       Name  Gender  Age       City Department    Salary               Email
0     Tariq    Male   47    Karachi     Sales   $123,609   tariq76@gmail.com
1      Hina  Female   26     Quetta         HR  $125,683    hina90@gmail.com
2     Usman    Male   36     lahore     Sales    $94,056   usman71@gmail.com
3      Sana  Female   21     Quetta    Finance  $147,901    sana72@gmail.com
4    Ayesha    Male   40     lahore         HR  $123,880  ayesha25@gmail.com
..      ...     ...  ...        ...        ...       ...                 ...
495    Zara  Female   56     quetta         IT   $94,056    zara35@gmail.com
496   Usman    Male   41     Lahore      Sales  $107,909   usman20@gmail.com
497   Ahmed    Male   20  Islamabad      Sales   $94,056   ahmed99@gmail.com
498   Ahmed  Female   41     Lahore         IT   $82,915   ahmed80@gmail.com
499   Tariq    Male   41  Islamabad    Finance  $122,337   tariq64@gmail.com

[500 rows x 7 columns]

In [25]:
df["City"] = df["City"].str.title()

In [26]:
df

       Name  Gender  Age       City Department    Salary               Email
0     Tariq    Male   47    Karachi     Sales   $123,609   tariq76@gmail.com
1      Hina  Female   26     Quetta         HR  $125,683    hina90@gmail.com
2     Usman    Male   36     Lahore     Sales    $94,056   usman71@gmail.com
3      Sana  Female   21     Quetta    Finance  $147,901    sana72@gmail.com
4    Ayesha    Male   40     Lahore         HR  $123,880  ayesha25@gmail.com
..      ...     ...  ...        ...        ...       ...                 ...
495    Zara  Female   56     Quetta         IT   $94,056    zara35@gmail.com
496   Usman    Male   41     Lahore      Sales  $107,909   usman20@gmail.com
497   Ahmed    Male   20  Islamabad      Sales   $94,056   ahmed99@gmail.com
498   Ahmed  Female   41     Lahore         IT   $82,915   ahmed80@gmail.com
499   Tariq    Male   41  Islamabad    Finance  $122,337   tariq64@gmail.com

[500 rows x 7 columns]

In [27]:
df.isnull().sum()

Name          0
Gender        0
Age           0
City          0
Department    0
Salary        0
Email         0
dtype: int64

In [28]:
df.dtypes

Name          object
Gender        object
Age            int64
City          object
Department    object
Salary        object
Email         object
dtype: object